<a href="https://colab.research.google.com/github/JosephBigDataAnalytics/JKaremera-Programming-BigDataAnalytics/blob/main/Task_10_complete.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 10 Executive summary

Gemini's Vision Language Model was evaluated on 15 receipt images to assess its ability to extract total prices via OCR. The model achieved a 53.3% extraction success rate, successfully processing 8 of 15 receipts. Where predictions were made, performance was flawless — a Mean Absolute Error of $0.00 and 100% accuracy within both the 5% and 10% thresholds, meaning every successful prediction matched the ground truth exactly. However, the 7 failed extractions (46.7%) due to issues with API key. Improving pre-processing and prompt engineering could substantially raise the overall success rate.

Imports and configurations

In [ ]:
import os
import re
import zipfile
import json
import pandas as pd
import numpy as np
from pathlib import Path
from google import genai
from google.genai import types

# ── CONFIG ────────────────────────────────────────────────────────────────────
GEMINI_API_KEY = "AIzaSyBBJI9fFuDvSTGVzJse59wtNEk291xF_z8"
ZIP_PATH       = "/content/receipts_sample.zip"
EXTRACT_DIR    = "//content/receipts_sample"
GEMINI_MODEL   = "gemini-2.5-flash"
SAMPLE_SIZE    = 15
RANDOM_SEED    = 42
THRESHOLD_PCT  = 0.10   # 10% accuracy threshold
# ─────────────────────────────────────────────────────────────────────────────

client = genai.Client(api_key=GEMINI_API_KEY)

unzip file

In [ ]:
os.makedirs(EXTRACT_DIR, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    z.extractall(EXTRACT_DIR)

# Preview extracted structure to understand layout
all_files = list(Path(EXTRACT_DIR).rglob("*"))
print(f"Total files extracted: {len(all_files)}")
print("Sample files:")
for f in all_files[:20]:
    print(" ", f)

Total files extracted: 1431
Sample files:
  //content/receipts_sample/receipts_sample
  //content/receipts_sample/receipts_sample/receipt_sample_703.jpg
  //content/receipts_sample/receipts_sample/receipt_sample_432.txt
  //content/receipts_sample/receipts_sample/receipt_sample_089.jpg
  //content/receipts_sample/receipts_sample/receipt_sample_371.txt
  //content/receipts_sample/receipts_sample/receipt_sample_382.jpg
  //content/receipts_sample/receipts_sample/receipt_sample_252.txt
  //content/receipts_sample/receipts_sample/receipt_sample_655.jpg
  //content/receipts_sample/receipts_sample/receipt_sample_441.txt
  //content/receipts_sample/receipts_sample/receipt_sample_226.txt
  //content/receipts_sample/receipts_sample/receipt_sample_518.txt
  //content/receipts_sample/receipts_sample/receipt_sample_001.txt
  //content/receipts_sample/receipts_sample/receipt_sample_426.txt
  //content/receipts_sample/receipts_sample/receipt_sample_336.jpg
  //content/receipts_sample/receipts_sample/receipt_sample_221.txt
  //content/receipts_sample/receipts_sample/receipt_sample_008.jpg
  //content/receipts_sample/receipts_sample/receipt_sample_445.txt
  //content/receipts_sample/receipts_sample/receipt_sample_506.jpg
  //content/receipts_sample/receipts_sample/receipt_sample_100.txt
  //content/receipts_sample/receipts_sample/receipt_sample_326.txt

Parse ground truth

In [ ]:
def parse_total_from_txt(txt_path: Path) -> float | None:
    """
    Tries three common ground-truth text file formats:
      Format A — key:value pairs   e.g.  total_price:12.99
      Format B — JSON              e.g.  {"total_price": 12.99}
      Format C — bare float        e.g.  12.99
    Returns the total_price as float, or None if not found.
    """
    try:
        content = txt_path.read_text(encoding="utf-8").strip()

        # ── Format B: JSON ────────────────────────────────────────────────────
        # Handle cases where the JSON is wrapped in an outer string literal (e.g., "\"{\"key\":\"value\"}\"")
        json_content_to_parse = content
        if content.startswith('"') and content.endswith('"'):
            try:
                # Attempt to unquote the string to get the actual JSON string
                json_content_to_parse = json.loads(content)
            except json.JSONDecodeError:
                # If it's not a valid JSON string literal, keep original content
                pass

        if json_content_to_parse.startswith("{"):
            try:
                data = json.loads(json_content_to_parse)
                # Handle nested structures: {"total": {"value": 12.99}} or flat
                for key in ["total_price", "total", "amount_due",
                            "grand_total", "Total", "TOTAL"]:
                    if key in data:
                        val = data[key]
                        if isinstance(val, dict):
                            val = val.get("value") or val.get("text") or val.get("amount")
                        # Handle cases like "6.65 6.65 6.65" by extracting the first float
                        if isinstance(val, str):
                            match = re.search(r"[\d,]+\.?\d*", val)
                            if match:
                                return float(match.group().replace(",", "").replace("$", ""))
                            else:
                                return None
                        return float(str(val).replace(",", "").replace("$", ""))
                return None
            except json.JSONDecodeError:
                pass # Not valid JSON, fall through to other formats

        # ── Format A: key:value or key = value lines ──────────────────────────
        for line in content.splitlines():
            line_lower = line.lower()
            if any(kw in line_lower for kw in
                   ["total_price", "total price", "grand total",
                    "amount due", "total due", "amount_due"]):
                # Extract the numeric part after the colon/equals/tab
                match = re.search(r"[:=\t]\s*\$?([\d,]+\.?\d*)", line)
                if match:
                    return float(match.group(1).replace(",", ""))

        # ── Format C: bare float / single number ──────────────────────────────
        match = re.search(r"^\$?([\d,]+\.\d{2})$", content)
        if match:
            return float(match.group(1).replace(",", ""))

    except Exception as e:
        print(f"  ⚠️  Could not parse {txt_path.name}: {e}")

    return None


# ── Build df_receipt by pairing images with their .txt ground truth ───────────
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tiff"}

records = []
for img_file in sorted(Path(EXTRACT_DIR).rglob("*")):
    if img_file.suffix.lower() not in IMAGE_EXTENSIONS:
        continue

    # Look for matching .txt in the same directory as the image
    txt_file = img_file.with_suffix(".txt")

    if not txt_file.exists():
        # Also search one level up (some datasets store labels in sibling folder)
        txt_file = img_file.parent.parent / "labels" / (img_file.stem + ".txt")

    total_price = parse_total_from_txt(txt_file) if txt_file.exists() else None

    records.append({
        "receipt_id" : img_file.stem,
        "image_path" : str(img_file),
        "txt_path"   : str(txt_file) if txt_file.exists() else None,
        "total_price": total_price,
    })

df_receipt = pd.DataFrame(records)

# Diagnostic summary
n_with_gt  = df_receipt["total_price"].notna().sum()
n_missing  = df_receipt["total_price"].isna().sum()
print(f"\nTotal receipts  : {len(df_receipt)}")
print(f"With ground truth: {n_with_gt}")
print(f"Missing GT       : {n_missing}")

if n_missing > 0:
    print("\n⚠️  Missing GT rows (first 5):")
    print(df_receipt[df_receipt["total_price"].isna()][["receipt_id", "txt_path"]].head())

df_receipt.head(5)

Total receipts  : 714
With ground truth: 632
Missing GT       : 82

⚠️  Missing GT rows (first 5):
            receipt_id                                           txt_path
12  receipt_sample_012  //content/receipts_sample/receipts_sample/rece...
19  receipt_sample_019  //content/receipts_sample/receipts_sample/rece...
20  receipt_sample_020  //content/receipts_sample/receipts_sample/rece...
29  receipt_sample_029  //content/receipts_sample/receipts_sample/rece...
33  receipt_sample_033  //content/receipts_sample/receipts_sample/rece...

,receipt_id,image_path,txt_path,total_price
0,receipt_sample_000,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,6.65
1,receipt_sample_001,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,85.06
2,receipt_sample_002,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,19.74
3,receipt_sample_003,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,47.52
4,receipt_sample_004,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,38000.00

In [ ]:
# Debugging parse_total_from_txt function

# Choose a sample .txt file that is failing to parse
sample_txt_path = Path(df_receipt.loc[0, 'txt_path']) # Using the first file from df_receipt

if sample_txt_path.exists():
    print(f"Content of {sample_txt_path.name}:\n---\n{sample_txt_path.read_text()}\n---")
    extracted_total = parse_total_from_txt(sample_txt_path)
    print(f"Parsed total price for {sample_txt_path.name}: {extracted_total}")
    if extracted_total is None:
        print("\n  💡 Hint: The 'parse_total_from_txt' function returned None. You need to adjust the function in cell FhaF-fuQO5KX to match the format of the content above.")
else:
    print(f"Error: The sample .txt file '{sample_txt_path}' does not exist.")

Content of receipt_sample_000.txt:
---
"{\"store_name\": \"\", \"store_addr\": \"\", \"telephone\": \"\", \"date\": \"18/01/2018\", \"time\": \"13:51:56\", \"subtotal\": \"\", \"tax\": \"1.11\", \"total\": \"6.65 6.65 6.65\", \"ignore\": \"\", \"tips\": \"\", \"line_items\": [{\"item_key\": \"\", \"item_name\": \"HOTCHOCOLATE\", \"item_value\": \"2.40\", \"item_quantity\": \"1\"}, {\"item_key\": \"\", \"item_name\": \"HOTWRAPFALAFELHALOUMI\", \"item_value\": \"4.25\", \"item_quantity\": \"1\"}]}"
---
Parsed total price for receipt_sample_000.txt: 6.65

sample 15 records with valid ground truth

In [ ]:
df_filtered = df_receipt.dropna(subset=["total_price"])

if df_filtered.empty:
    print("Error: Cannot sample receipts. No entries with valid 'total_price' were found after filtering.")
    print("This indicates an issue with the 'parse_total_from_txt' function, which is expected to extract values from the .txt files.")
    print("Please review the 'parse_total_from_txt' function in the previous cell (FhaF-fuQO5KX) and the content of the ground truth (.txt) files.")
    # Create an empty DataFrame with the expected columns to allow subsequent cells to run gracefully
    expected_cols = df_receipt.columns.tolist() + ["predicted_total_price"]
    df_test_receipts = pd.DataFrame(columns=expected_cols)
    print("\nSkipping sampling as no valid ground truth receipts are available.")
else:
    df_test_receipts = (
        df_filtered
        .sample(n=SAMPLE_SIZE, random_state=RANDOM_SEED)
        .reset_index(drop=True)
    )
    print(f"Test set: {len(df_test_receipts)} receipts")
    df_test_receipts[["receipt_id", "total_price", "txt_path"]].head()

Test set: 15 receipts

In [ ]:
df_test_receipts.head()

,receipt_id,image_path,txt_path,total_price
0,receipt_sample_374,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,18.75
1,receipt_sample_276,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,165.00
2,receipt_sample_645,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,147.60
3,receipt_sample_162,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,141.00
4,receipt_sample_558,//content/receipts_sample/receipts_sample/rece...,//content/receipts_sample/receipts_sample/rece...,46.54

Gemni prompt and inference helper

In [ ]:
PROMPT = (
    "Extract the total amount due from this receipt. "
    "Respond with ONLY a single numerical value as a float (e.g. 12.99). "
    "Do not include currency symbols, words, or any other text."
)

MIME_MAP = {".jpg": "image/jpeg", ".jpeg": "image/jpeg",
            ".png": "image/png",  ".webp": "image/webp",
            ".bmp": "image/bmp",  ".tiff": "image/tiff"}

def predict_total_price(image_path: str) -> float | None:
    try:
        with open(image_path, "rb") as f:
            image_bytes = f.read()
        mime_type = MIME_MAP.get(Path(image_path).suffix.lower(), "image/jpeg")

        response = client.models.generate_content(
            model=GEMINI_MODEL,
            contents=[
                types.Part.from_bytes(data=image_bytes, mime_type=mime_type),
                PROMPT,
            ],
        )
        raw = response.text.strip()
        match = re.search(r"[\d,]+\.?\d*", raw)
        return float(match.group().replace(",", "")) if match else None

    except Exception as e:
        print(f"  ⚠️  Error on {Path(image_path).name}: {e}")
        return None

In [ ]:
predictions = []
for idx, row in df_test_receipts.iterrows():
    print(f"[{idx+1:02d}/{SAMPLE_SIZE}] {row['receipt_id']}  GT={row['total_price']:.2f}", end="  →  ")
    pred = predict_total_price(row["image_path"])
    print(f"Pred={pred}")
    predictions.append(pred)

df_test_receipts["predicted_total_price"] = predictions

[01/15] receipt_sample_374  GT=18.75  →  Pred=18.75
[02/15] receipt_sample_276  GT=165.00  →  Pred=165.0
[03/15] receipt_sample_645  GT=147.60  →  Pred=147.6
[04/15] receipt_sample_162  GT=141.00  →  Pred=141.0
[05/15] receipt_sample_558  GT=46.54  →  Pred=46.54
[06/15] receipt_sample_460  GT=77.60  →  Pred=77.6
[07/15] receipt_sample_184  GT=26.11  →  Pred=26.11
[08/15] receipt_sample_086  GT=625.50  →    ⚠️  Error on receipt_sample_086.jpg: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 21.249325508s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '21s'}]}}
Pred=None
[09/15] receipt_sample_599  GT=65.39  →    ⚠️  Error on receipt_sample_599.jpg: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 21.103395087s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '21s'}]}}
Pred=None
[10/15] receipt_sample_182  GT=12.61  →    ⚠️  Error on receipt_sample_182.jpg: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 20.887522115s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '20s'}]}}
Pred=None
[11/15] receipt_sample_304  GT=29.99  →  Pred=29.99
[12/15] receipt_sample_036  GT=0.00  →    ⚠️  Error on receipt_sample_036.jpg: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 18.445455835s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '18s'}]}}
Pred=None
[13/15] receipt_sample_063  GT=18.02  →    ⚠️  Error on receipt_sample_063.jpg: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 18.203114365s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '18s'}]}}
Pred=None
[14/15] receipt_sample_100  GT=135.90  →    ⚠️  Error on receipt_sample_100.jpg: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 18.063155331s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '18s'}]}}
Pred=None
[15/15] receipt_sample_650  GT=106.98  →    ⚠️  Error on receipt_sample_650.jpg: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 5, model: gemini-2.5-flash\nPlease retry in 17.815288647s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerMinutePerProjectPerModel-FreeTier', 'quotaDimensions': {'location': 'global', 'model': 'gemini-2.5-flash'}, 'quotaValue': '5'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '17s'}]}}
Pred=None

Evaluation metrics

In [ ]:
df_eval = df_test_receipts.dropna(subset=["predicted_total_price"]).copy()
df_eval[["total_price", "predicted_total_price"]] = df_eval[
    ["total_price", "predicted_total_price"]].apply(pd.to_numeric, errors="coerce")
df_eval.dropna(subset=["total_price", "predicted_total_price"], inplace=True)

n_total      = len(df_test_receipts)
n_success    = len(df_eval)
mae          = np.mean(np.abs(df_eval["total_price"] - df_eval["predicted_total_price"]))
pct_errors   = np.abs(df_eval["total_price"] - df_eval["predicted_total_price"]) / df_eval["total_price"]
acc_10       = (pct_errors <= 0.10).mean() * 100
acc_5        = (pct_errors <= 0.05).mean() * 100

print("=" * 50)
print("       GEMINI OCR — EVALUATION RESULTS")
print("=" * 50)
print(f"  Receipts tested          : {n_total}")
print(f"  Successful extractions   : {n_success} ({n_success/n_total*100:.1f}%)")
print(f"  Mean Absolute Error (MAE): ${mae:.2f}")
print(f"  Accuracy within  5%      : {acc_5:.1f}%")
print(f"  Accuracy within 10%      : {acc_10:.1f}%")
print("=" * 50)

==================================================
       GEMINI OCR — EVALUATION RESULTS
==================================================
  Receipts tested          : 15
  Successful extractions   : 8 (53.3%)
  Mean Absolute Error (MAE): $0.00
  Accuracy within  5%      : 100.0%
  Accuracy within 10%      : 100.0%
==================================================

side by side comparison table

In [ ]:
df_test_receipts["abs_error"]    = (df_test_receipts["total_price"] -
                                    df_test_receipts["predicted_total_price"]).abs()
df_test_receipts["pct_error"]    = (df_test_receipts["abs_error"] /
                                    df_test_receipts["total_price"] * 100).round(2)
df_test_receipts["within_10pct"] = df_test_receipts["pct_error"].apply(
    lambda x: "✅" if pd.notna(x) and x <= 10 else "❌")

display(df_test_receipts[[
    "receipt_id", "total_price",
    "predicted_total_price", "abs_error",
    "pct_error", "within_10pct"
]])

,receipt_id,total_price,predicted_total_price,abs_error,pct_error,within_10pct
0,receipt_sample_374,18.75,18.75,0.0,0.0,✅
1,receipt_sample_276,165.00,165.00,0.0,0.0,✅
2,receipt_sample_645,147.60,147.60,0.0,0.0,✅
3,receipt_sample_162,141.00,141.00,0.0,0.0,✅
4,receipt_sample_558,46.54,46.54,0.0,0.0,✅
5,receipt_sample_460,77.60,77.60,0.0,0.0,✅
6,receipt_sample_184,26.11,26.11,0.0,0.0,✅
7,receipt_sample_086,625.50,NaN,NaN,NaN,❌
8,receipt_sample_599,65.39,NaN,NaN,NaN,❌
9,receipt_sample_182,12.61,NaN,NaN,NaN,❌
10,receipt_sample_304,29.99,29.99,0.0,0.0,✅
11,receipt_sample_036,0.00,NaN,NaN,NaN,❌
12,receipt_sample_063,18.02,NaN,NaN,NaN,❌
13,receipt_sample_100,135.90,NaN,NaN,NaN,❌
14,receipt_sample_650,106.98,NaN,NaN,NaN,❌